Flow Controller:
    name: MiNiFi Flow

Processors:
    - name: GetFile
      class: org.apache.nifi.processors.standard.GetFile
      max concurrent tasks: 1
      scheduling strategy: TIMER_DRIVEN
      scheduling period: 1 sec
      penalization period: 30 sec
      yield period: 1 sec
      run duration nanos: 0
      auto-terminated relationships list:
      Properties:
          Input Directory: /tmp/getfile
          Keep Source File: true

Connections:
    - name: TransferFilesToRPG
      source name: GetFile
      source relationship name: success
      destination name: 08755c4f-0159-1000-c1be-b46373f25d80
      max work queue size: 0
      max work queue data size: 1 MB
      flowfile expiration: 60 sec

Remote Processing Groups:
    - name: NiFi Flow
      url: http://nifi.dev:8080/nifi
      timeout: 30 secs
      yield period: 10 sec
      Input Ports:
          - id: 08755c4f-0159-1000-c1be-b46373f25d80
            name: MiNiFiData
            max concurrent tasks: 1
            Properties:
                Port: 9191
                Host Name: nifi.dev
      Output Ports:
          - id: 37052b39-0159-1000-1f78-9025cb040b29
            name: ToMiNiFi
            max concurrent tasks: 1
            Properties:
                Port: 9191
                Host Name: nifi.dev